path: config/main.dol
r13: 0x8041cf20
r2: 0x80427440
section_defs:
  text:
    - name: .init
    - name: .text
  data:
    - name: .ctors
    - name: .dtors
    - name: .rodata
    - name: .data
    - name: .sdata
    - name: .sdata2
  bss:
    - name: .bss
    - name: .sbss
    - name: .sbss2
      nobits: true
      
      